# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oil4eyzMWkpWHBorsrGh12OPpt6OC6-1
"""

pip isntall opency-pyton

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread('Rasm.jpg')
rasm=cv2.imread('Rasm1.jpg')
rasm=cv2.imread('Rasm2.jpg')
rasm=cv2.imread('Rasm3.jpg')
rasm=cv2.imread('Rasm4.png')
cv2_imshow(rasm)